{{- $fullName := include "chatterbox.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
data:
  discord-token: {{ .Values.discord.token | b64enc }}
  discord-owner-id: {{ .Values.discord.ownerId | replace ":" "" | b64enc }}
  database-username: {{ .Values.database.username | b64enc }}
  database-password: {{ .Values.database.password | b64enc }}