replicaCount: 1

image:
  repository: ghcr.io/rmmorrison/chatterbox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

discord:
  token: ""
  ownerId: ""

commands:
  prefix: "!"
  alternatePrefix: .

database:
  url: jdbc:mysql://localhost:3306/chatterbox?createDatabaseIfNotExist=true
  username: ""
  password: ""
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: MYSQL

